# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTifq6bX6VMa8g9aSXSxYKxglNDkTKDK
"""

!wget https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

#загрузка библиотек
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#установка стиля графиков
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("Set2")

#загрузка данных
df = pd.read_csv('titanic.csv')


print("MLP-КЛАССИФИКАТОР ДЛЯ ПРЕДСКАЗАНИЯ ВЫЖИВАЕМОСТИ (титаник)")


#выбор признаков для анализа
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
target = 'Survived'

X = df[features]
y = df[target]

print(f"\n Размер данных: {X.shape[0]} строк, {X.shape[1]} признаков")
print(f"Признаки: {features}")
print(f" Целевая переменная: {target}")

# обучение и тестовая выборка
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"\nОбучающая выборка: {X_train.shape[0]} строк")
print(f" Тестовая выборка: {X_test.shape[0]} строк")

# Полготовка данных
# Числовые признаки (с масштабированием)
numeric_features = ['Age', 'SibSp', 'Parch', 'Fare']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),      # заполнение пропусков медианой
    ('scaler', StandardScaler())                        # нормализация
])

# Категориальные признаки (с кодированием)
categorical_features = ['Pclass', 'Sex', 'Embarked']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),  # заполнение пропусков
    ('onehot', OneHotEncoder(drop='first'))                # кодировка
])

# Объединение в один препроцессор
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# ПРОЦЕСС СОЗДАНИЯ И ОБУЧЕНИЯ МОДЕЛИ
# добавил параметр verbose=True, чтобы видеть процесс обучения
model = MLPClassifier(
    hidden_layer_sizes=(100, 50),   # Два скрытых слоя: 100 и 50 нейронов
    activation='relu',              # Функция активации ReLU
    solver='adam',                  # Оптимизатор Adam
    max_iter=500,                   # Максимум
    random_state=42,                # Фиксируем случайность
    early_stopping=True,            # Ранняя остановка
    validation_fraction=0.1,        # 10% на валидацию
    n_iter_no_change=10,            # Останавливаемся после 10  без улучшений
    verbose=True                    # Показываем прогресс обучения
)

#конвейер
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', model)
])

# Обучение модели
print("\n" )
print(" НАЧАЛО ОБУЧЕНИЯ ")

pipeline.fit(X_train, y_train)


#ПОСТРОЕНИЕ ГРАФИКОВ ОБУЧЕНИЯ

# MLPClassifier сохраняет историю потерь  в атрибуте loss_curve_
# история валидационных потерь в validation_scores_

# история обучения
loss_curve = model.loss_curve_  # Потери на обучающей выборке

# Для валидационных потерь нужно преобразовать validation_scores_
if hasattr(model, 'validation_scores_'):
    val_scores = model.validation_scores_
    val_loss = [1 - score for score in val_scores]
    epochs_val = range(1, len(val_loss) + 1)
else:
    val_loss = None

epochs_train = range(1, len(loss_curve) + 1)

#  фигура с двумя подграфиками
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

#  График 1 Кривая обучения (потери именно )
axes[0].plot(epochs_train, loss_curve, 'b-', linewidth=2, label='Обучающая выборка', color='#2E86AB')
if val_loss:
    axes[0].plot(epochs_val, val_loss, 'r--', linewidth=2, label='Валидационная выборка', color='#D64933')
axes[0].set_xlabel('Эпоха', fontsize=12)
axes[0].set_ylabel('Потери', fontsize=12)
axes[0].set_title('Кривая обучения нейронной сети\n(снижение потерь = улучшение модели)', fontsize=12)
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# График 2 Точность на валидации (если есть данные)
if val_loss:
    val_accuracy = val_scores  # Это уже точность
    axes[1].plot(epochs_val, val_accuracy, 'g-', linewidth=2, marker='o', markersize=4, color='#2E86AB')
    axes[1].set_xlabel('Эпоха', fontsize=12)
    axes[1].set_ylabel('Точность ', fontsize=12)
    axes[1].set_title('Динамика точности на валидационной выборке', fontsize=12)
    axes[1].grid(True, alpha=0.3)
    # Добавляем линию порога 75% чтобы улучшить результат
    axes[1].axhline(y=0.75, color='r', linestyle='--', alpha=0.7, label='Целевой порог (75%)')
    axes[1].legend()
else:
    axes[1].text(0.5, 0.5, 'Нет данных о валидации',
                 ha='center', va='center', transform=axes[1].transAxes)
    axes[1].set_title('Валидационные данные недоступны')

plt.suptitle('Анализ процесса обучения MLP-классификатора', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Оценка качества модели
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("\n")
print(" РЕЗУЛЬТАТЫ РАБОТЫ МОДЕЛИ")
print(f" Точность на тестовых данных : {accuracy:.4f}")

if accuracy > 0.75:
    print(" Модель исправна, Точность > 75%")
else:
    print(" Точность менее 75%. Попробуйте увеличить max_iter или hidden_layer_sizes.")

print("\nДетальный отчет классификации")
print(classification_report(y_test, y_pred))

# Визуализация матрицы ошибок
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Погиб', 'Выжил'],
            yticklabels=['Погиб', 'Выжил'])
plt.title('Матрица ошибок ', fontsize=12, fontweight='bold')
plt.ylabel('Реальное значение', fontsize=11)
plt.xlabel('Предсказанное значение', fontsize=11)
plt.tight_layout()
plt.show()