# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QEfZL9EkVQrGuzbD7WziPAF9yW72eLW
"""

#ТЕПЛОВАЯ КАРТА КОРРЕЛЯЦИЙ ДАННЫХ TITANIC

#---------------------------------------------------------------------
# Установка библиотек
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Настройка стиля графиков
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("coolwarm")

# загрузка данных с гитхаба------------------------------------------
import urllib.request
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
try:
    urllib.request.urlretrieve(url, "titanic.csv")
    print("Файл titanic.csv успешно загружен")
except:
    print("Не удалось скачать файл")


# первичный анализ данных---------------------------------------------
print("ПЕРВИЧНЫЙ АНАЛИЗ ДАННЫХ")

print(f"\nРазмер данных: {df.shape[0]} строк, {df.shape[1]} столбцов")
print("\nПервые 5 строк данных:")
print(df.head())

print("\n Типы данных:")
print(df.dtypes)

print("\n Статистика по числовым колонкам:")
print(df.describe())

# подготовка для корреляции--------------------------------------

# копия для работы
df_corr = df.copy()

# Перекодируем пол в число (0 - муж, 1 - жен)
df_corr['Sex'] = df_corr['Sex'].map({'male': 0, 'female': 1})

# Перекодируем порт посадки в числа
# S=0, C=1, Q=2
df_corr['Embarked'] = df_corr['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

print("\n Данные подготовлены для корреляционного анализа")
print("Пол перекодирован: male=0, female=1")
print("Порт посадки перекодирован: S=0, C=1, Q=2")

# ВЫбор колонок для корреляции----------------------------------

# Выбрал только числовые колонки, которые имеют смысл для анализа
columns_for_corr = ['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

# Проверяем, какие колонки есть в данных
available_columns = [col for col in columns_for_corr if col in df_corr.columns]
print(f"\nКолонки для корреляционного анализа: {available_columns}")

# Берем только нужные колонки
df_corr_selected = df_corr[available_columns]

# расчет матрицы корреляций-------------------------------------

# Считаем корреляцию Пирсона (стандартная корреляция)
corr_matrix = df_corr_selected.corr(method='pearson')

# Округляем для красивого вывода
corr_matrix_rounded = corr_matrix.round(2)

print("МАТРИЦА КОРРЕЛЯЦИЙ")
print(corr_matrix_rounded)

# ПОстроение тепловой карты------------------------------------------

# Создаем фигуру
plt.figure(figsize=(10, 8))

# Строим тепловую карту
heatmap = sns.heatmap(
    corr_matrix,                    #  матрица корреляций
    annot=True,                     # Показывать числа внутри ячеек
    fmt='.2f',                      # Формат чисел 2 знака после запятой
    cmap='coolwarm',                # Цветовая схема красный к +, синий к -
    center=0,                       # Центр палитры — 0
    square=True,                    # Квадратные ячейки
    linewidths=0.5,                 # Тонкие линии между ячейками
    linecolor='white',              # Цвет линий
    cbar_kws={"shrink": 0.8, "label": "Коэффициент корреляции"},  # Настройки шкалы
    annot_kws={"size": 10}          # Размер шрифта чисел
)

# Настройка заголовка и подписей
plt.title('Тепловая карта корреляций характеристик пассажиров Титаника\n(красный = +, синий = -, чем ярче, тем сильнее связь)',
          fontsize=14, fontweight='bold', pad=20)

# Поворачиваем подписи, чтобы не налезали
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.yticks(rotation=0, fontsize=11)

# Добавляем сетку для удобства чтения
plt.tight_layout()


# Показываем график
plt.show()

# Анализ корреляции------------------------------------------------------------


print("АНАЛИЗ МАТРИЦЫ КОРРЕЛЯЦИЙ")

# Сортируем корреляции  по убыванию
survived_corr = corr_matrix['Survived'].drop('Survived').sort_values(ascending=False)
print("\nВлияние признаков на выживаемость (от самого сильного к слабому):")
for feature, corr_value in survived_corr.items():
    if corr_value > 0:
        direction = " ПОЛОЖИТЕЛЬНАЯ"
    elif corr_value < 0:
        direction = "ОТРИЦАТЕЛЬНАЯ"
    else:
        direction = " НЕТ"
    print(f"   {feature:10} : {corr_value:6.2f}  ({direction})")